---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r import_packages}
library(here)
library(tidyverse)
library(DT)
library(rmarkdown)
library(googlesheets4)
```

```{r import_fxns}
source("scripts/format-tables.R")
#query collection should be run from the workflows
```

```{r import_subset_data}
full_repo_df <- read_tsv(here("resources/collection.tsv"))
full_repo_df$CurrentOrFuture = "Current"
full_repo_df <- full_repo_df %>% filter(!grepl(":", CourseName))
```

```{r drive_single_pages, results='hide'}
for (i in 1:nrow(full_repo_df)){
  courseOI <- full_repo_df$CourseName[i]
  if (courseOI != "AI for Decision Makers"){
    rmarkdown::render(input = "single_course_template.Rmd", output_file = paste0(full_repo_df$name[i], "_coursePage.html"), params = list(course_name = courseOI, row_number = i))
  } else{
    rmarkdown::render(input = "ai_course_template.Rmd", output_file = "AI_for_Decision_Makers_coursePage.html")
  }
}
```

```{r wrangle_data}
wrangled <- full_repo_df %>%
  mutate(Concepts = str_to_title(Concepts),
         Concepts = str_replace_all(Concepts, "Ai", "AI"),
         Concepts = str_replace_all(Concepts, "Ci-Cd", "Continuous Integration/Continuous Deployment"),
         Concepts = str_replace_all(Concepts, "Nih", "NIH"),
         Concepts = str_replace_all(Concepts, "Hipaa", "HIPAA"),
         Concepts = str_replace_all(Concepts, "Llm", "LLM"),
         Concepts = str_replace_all(Concepts, "Phi", "(PHI)"),
         Concepts = str_replace_all(Concepts, "Pii", "(PII)"),
         Concepts = str_replace_all(Concepts, "Arxiv", "ArXiv"),
         Concepts = str_replace_all(Concepts, "Latex", "LaTeX"),
         Concepts = str_replace_all(Concepts, "And", "&"),
         Concepts = str_replace_all(Concepts, "Iv", "IV"),
         Concepts = str_replace_all(Concepts, "Iii", "III"),
         Concepts = str_replace_all(Concepts, "Ii", "II")
        )
```

```{r}
gs4_deauth()
```

```{r join_additional_modalities}
modality_df <- read_sheet("https://docs.google.com/spreadsheets/d/1Dol8d16WF4see4JjGwt-ODj7QzRAuDeYixufNpxtWlM/edit?usp=sharing")

wrangled <- add_modalities(wrangled, modality_df)

```

```{r prep_table_wcat, eval=FALSE}
#this includes the category column
output_prep <- prep_table(wrangled, keep_category = TRUE) %>%
  mutate("Concepts Discussed" = str_replace_all(`Concepts Discussed`, "De Identification", "De-Identification"))

# See scripts/format-tables.R to see the function setup_table() for formatting details of the tables

output_table <- setup_table(output_prep, "Type in key words to find courses relevant for you. Click on filter arrows to sort.",
                            columnDefsListOfLists = list(list(className = 'dt-center', targets = c(0,1,2,4, 6)), #Course Name, Funding, Audience, Category, More Resources
                                                         list(className = "dt-left", targets = c(3,5)), #Description and concepts
                                                         list(width = '135px', targets = c(0)), #Course Name
                                                         list(width = '190px', targets = c(3)), #Description
                                                         list(width = '65px', targets = c(1)), # Funding
                                                         list(width = "65px", targets = c(2)), # Audience
                                                         list(width = "65px", targets = c(4)), # Category
                                                         list(width = "145px", targets = c(5)), # Concepts
                                                         list(width = "295px", targets = c(6)) #More Resources
                                                        )
                            )
```

<!-- And these are the column justifications and sizes I've got set right now if you include category column -->

<!-- | Column Name        | Location | Justified | Width         | Font size     |-->
<!-- | :----------------: | :------: | :-------: | :-----------: | :------------:|-->
<!-- | Course Name        | 0        | Center    | 135px         | 12pt          |-->
<!-- | Funding            | 1        | Center    | 65px          | Not Specified |-->
<!-- | Broad Audience     | 2        | Center    | 65px          | 10px          |-->
<!-- | Description        | 3        | Left      | 190px         | Not Specified |-->
<!-- | Category           | 4        | Center    | 65px          | 10px          |-->
<!-- | Concepts Discussed | 5        | Left      | 145px         | Not Specified |-->
<!-- | More Resources     | 6        | Center    | 295px         | Not Specified |-->

<!-- Font sizes are specified in the format-tables.R file (for Course Name column) and the styles.css file (for Broad Audience and Category columns) -->

```{r prep_table_wocat, eval=TRUE}
#this excludes the category column
output_prep <- prep_table(wrangled, keep_category = FALSE) %>%
  mutate("Concepts Discussed" = str_replace_all(`Concepts Discussed`, "De Identification", "De-Identification"))

# See scripts/format-tables.R to see the function setup_table() for formatting details of the tables

output_table <- setup_table(output_prep, "Type in key words to find courses relevant for you. Click on filter arrows to sort.",
                            columnDefsListOfLists = list(list(className = 'dt-center', targets = c(0,1,2, 5)), #Course Name, Funding, Audience, Category, More Resources
                                                         list(className = "dt-left", targets = c(3,4)), #Description and concepts
                                                         list(width = '135px', targets = c(0)), #Course Name
                                                         list(width = '200px', targets = c(3)), #Description
                                                         list(width = '85px', targets = c(1)), # Funding
                                                         list(width = "95px", targets = c(2)), # Audience
                                                         list(width = "150px", targets = c(4)), # Concepts
                                                         list(width = "295px", targets = c(5)) #More Resources
                                                        )
                            )
```

<!-- And these are the column justifications and sizes I've got set right now if you don't include the category column-->

<!-- | Column Name        | Location | Justified | Width         | Font size     |-->
<!-- | :----------------: | :------: | :-------: | :-----------: | :------------:|-->
<!-- | Course Name        | 0        | Center    | 135px         | 12pt          |-->
<!-- | Funding            | 1        | Center    | 85px          | Not Specified |-->
<!-- | Broad Audience     | 2        | Center    | 95px          | 14px          |-->
<!-- | Description        | 3        | Left      | 200px         | Not Specified |-->
<!-- | Concepts Discussed | 4        | Left      | 150px         | Not Specified |-->
<!-- | More Resources     | 5        | Center    | 295px         | Not Specified |-->

<!-- Font sizes are specified in the format-tables.R file (for Course Name column) and the styles.css file (for Broad Audience and Category columns) -->

```{r display_table}
output_table
```


<!-- This is the URL that the Hutch logo goes to: https://www.fredhutch.org/en/about/about-the-hutch.html -->

<!-- This is the URL that the ITCR logo goes to: https://itcr.cancer.gov -->


