
<hr>

### Necessary Pre-Requisites


<center>

:::warning
There are required prerequisites for this course!
:::

```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis', out.width="80%"}
if ({PREREQ_SLIDE_LINK} != "NA"){
  ottrpal::include_slide({PREREQ_SLIDE_LINK})
}
```



<br>

```{r}

# if the advanced course paste link in a span with larger font in html to intro course
if (str_detect({GITHUB_LINK}, pattern = "Adv_Reproducibility")){
  cat('<div class = blackbox>Please check out our [Introduction to Reproducibility Course](https://jhudatascience.org/Reproducibility_in_Cancer_Informatics).</div>')
}


# if the actions or containers course paste link in a span with larger font in html to intro and advanced course

if (str_detect({GITHUB_LINK}, pattern = "Automation|Containers")){cat('<div class = blackbox>Please check out our [Introduction to Reproducibility Course](https://jhudatascience.org/Reproducibility_in_Cancer_Informatics) and our [Advanced Reproducibility Course](https://jhudatascience.org/Adv_Reproducibility_in_Cancer_Informatics).</div>')
}

# if the capstone course, paste link in a span with larger font in html to intro, advanced, actions, and containers courses
if (str_detect({GITHUB_LINK}, pattern = "capstone")){
  cat('<div class = blackbox>Please check out our prerequisite courses: 
<br> - [Introduction to Reproducibility Course](https://jhudatascience.org/Reproducibility_in_Cancer_Informatics) 
<br> - [Advanced Reproducibility Course](https://jhudatascience.org/Adv_Reproducibility_in_Cancer_Informatics)
 <br> -[GitHub Automation for Scientists Course](https://hutchdatascience.org/GitHub_Automation_for_Scientists/)
 <br> -[Containers for Scientists Course](https://hutchdatascience.org/Containers_for_Scientists/).</div>')
}

```

</center>

<br>
