
<hr>

### Necessary Pre-Requisites


<center>

:::warning
There are required prerequisites for this course!
:::

```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis', out.width="80%"}
if ("https://docs.google.com/presentation/d/1ExTZsKDHKM0fIi0_tB80qd8cHvqjEDyNJp-OsnvZ19o/edit?slide=id.g366a6ed3497_0_211#slide=id.g366a6ed3497_0_211" != "NA"){
  ottrpal::include_slide("https://docs.google.com/presentation/d/1ExTZsKDHKM0fIi0_tB80qd8cHvqjEDyNJp-OsnvZ19o/edit?slide=id.g366a6ed3497_0_211#slide=id.g366a6ed3497_0_211")
}
```



<br>

```{r}

# if the advanced course past link in a span with larger font in html to intro course
if (str_detect("https://github.com/fhdsl/reproducibility_capstone", pattern = "Adv_Reproducibility")){
  cat('<div class = blackbox>Please check out our [Introduction to Reproducibility Course](https://jhudatascience.org/Reproducibility_in_Cancer_Informatics).</div>')
}


# if the actions or containers course past link in a span with larger font in html to intro and advanced course

if (str_detect("https://github.com/fhdsl/reproducibility_capstone", pattern = "Automation|Containers")){cat('<div class = blackbox>Please check out our [Introduction to Reproducibility Course](https://jhudatascience.org/Reproducibility_in_Cancer_Informatics) and our [Advanced Reproducibility Course](https://jhudatascience.org/Adv_Reproducibility_in_Cancer_Informatics).</div>')
}
```

</center>

<br>
